version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: azizbot
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: aziz_bot_db
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aziz_bot_network
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: aziz_bot_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9090:3000"
    environment:
        NODE_ENV : production
        PORT : 3000
      
        BOT_TOKEN: ${BOT_TOKEN}
        BOT_USERNAME: ${BOT_USERNAME}
        DATABASE_URL: postgresql://azizbot:your_strong_password@postgres:5432/aziz_bot_db?schema=public
        PAYME_MERCHANT_ID: ${PAYME_MERCHANT_ID:-}
        PAYME_KEY: ${PAYME_KEY:-}
        PAYME_TEST_KEY: ${PAYME_TEST_KEY:-}
        PAYME_ENDPOINT: ${PAYME_ENDPOINT:-https://checkout.paycom.uz}
      
        WEB_PANEL_URL: ${WEB_PANEL_URL}
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    networks:
      - aziz_bot_network
    command: sh -c "npx prisma db push && pnpm run start:dev"
    

networks:
  aziz_bot_network:
    driver: bridge
    name: aziz_bot_network

volumes:
  postgres_data:
    driver: local
    name: aziz_bot_postgres_data