version: "3.9"

services:
  db:
    image: postgres:16
    container_name: aziz_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: aziz_grammydb
    ports:
      - "5432:5432"
    volumes:
      - baza_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: aziz_bot
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        pnpm run build
        npx prisma generate &&
        npx prisma migrate deploy &&
        pnpm run start:prod
      "

  nginx:
    image: nginx:alpine
    container_name: aziz_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html/public
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app

volumes:
  baza_data:
